# Generated by Django 3.2 on 2021-07-05 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_dossier', models.CharField(blank=True, max_length=30, null=True)),
                ('recC', models.DateField(blank=True, null=True, verbose_name='Date de reception')),
                ('respC', models.TextField(blank=True, max_length=20, null=True)),
                ('decisionC', models.CharField(blank=True, choices=[('', ''), ('Accepté', 'Accepté'), ('Rejeté', 'Rejeté')], max_length=20, null=True)),
                ('pieces', models.TextField(blank=True, null=True)),
                ('complement', models.DateField(blank=True, null=True, verbose_name='Date de complément')),
                ('paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('prolongation', models.DateField(blank=True, null=True, verbose_name='Date de prolongation')),
                ('observationsC', models.TextField(blank=True, null=True)),
                ('dureeC', models.TextField(blank=True, max_length=30, null=True)),
                ('type_dossier', models.CharField(blank=True, choices=[('Marché', 'Marché'), ('Consultation', 'Consultation'), ('Gré à gré', 'Gré à gré'), ('', '')], max_length=20, null=True)),
                ('objet', models.TextField(blank=True, max_length=30, null=True)),
                ('lancement', models.DateField(blank=True, null=True, verbose_name='Date de lancement')),
                ('ouverture', models.DateField(blank=True, null=True, verbose_name="Date d'ouverture")),
                ('observationM', models.TextField(blank=True, null=True)),
                ('fournisseur', models.TextField(blank=True, max_length=30, null=True)),
                ('transmissionM', models.DateField(blank=True, null=True, verbose_name='Date de transmission')),
                ('decisionM', models.TextField(blank=True, choices=[('', ''), ('Accepté', 'Accepté'), ('Rejeté', 'Rejeté')], max_length=20, null=True)),
                ('convention', models.IntegerField(blank=True, default=0, null=True)),
                ('respM', models.TextField(blank=True, max_length=30, null=True)),
                ('dureeM', models.TextField(blank=True, max_length=30, null=True)),
                ('recCo', models.DateField(blank=True, null=True, verbose_name='Date de réception')),
                ('respCo', models.TextField(blank=True, max_length=30, null=True)),
                ('decisionCo', models.TextField(blank=True, choices=[('', ''), ('Accepté', 'Accepté'), ('Rejeté', 'Rejeté')], max_length=20, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('proformaCo', models.IntegerField(blank=True, default=0, null=True)),
                ('dproforma', models.DateField(blank=True, null=True, verbose_name='Date de facture proforma')),
                ('montant', models.FloatField(blank=True, default=0, null=True)),
                ('bonc', models.IntegerField(blank=True, null=True)),
                ('dbonc', models.DateField(blank=True, null=True, verbose_name='Date du bon de commande')),
                ('prestation', models.DateField(blank=True, null=True, verbose_name='Date de réception de la préstation')),
                ('définitive', models.IntegerField(blank=True, null=True)),
                ('bonr', models.IntegerField(blank=True, null=True)),
                ('transmission', models.DateField(blank=True, null=True, verbose_name='Date de transmission')),
                ('dureeCo', models.TextField(blank=True, max_length=30, null=True)),
                ('recB', models.DateField(blank=True, null=True, verbose_name='Date de réception')),
                ('respB', models.TextField(blank=True, max_length=30, null=True)),
                ('observationB', models.TextField(blank=True, null=True)),
                ('engagement', models.DateField(blank=True, null=True, verbose_name="Date d'engagement au CF")),
                ('motifs', models.TextField(blank=True, null=True)),
                ('visa', models.DateField(blank=True, null=True, verbose_name='Date de Visa/rejet')),
                ('transmissionB', models.DateField(blank=True, null=True, verbose_name='Date de transmission')),
                ('dureeB', models.TextField(blank=True, max_length=30, null=True)),
                ('mandatement', models.DateField(blank=True, null=True, verbose_name='Date de Mandatement')),
                ('pCo', models.FloatField(blank=True, null=True)),
                ('pM', models.FloatField(blank=True, null=True)),
                ('pB', models.FloatField(blank=True, null=True)),
                ('pC', models.FloatField(blank=True, null=True)),
                ('coulCo', models.TextField(blank=True, max_length=30, null=True)),
                ('coulM', models.TextField(blank=True, max_length=30, null=True)),
                ('coulC', models.TextField(blank=True, max_length=30, null=True)),
                ('coulB', models.TextField(blank=True, max_length=30, null=True)),
                ('service', models.TextField(blank=True, max_length=30, null=True)),
                ('motifClo', models.TextField(blank=True, max_length=30, null=True)),
                ('respClo', models.TextField(blank=True, max_length=30, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, default=0, null=True)),
                ('statut', models.TextField(blank=True, max_length=30, null=True)),
                ('duree', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('adresse', models.TextField(blank=True, null=True)),
                ('num', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
