# Generated by Django 3.2.9 on 2022-10-02 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=30, null=True, verbose_name='Désignation du lot')),
            ],
        ),
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(blank=True, max_length=30, null=True, verbose_name='Opérateur')),
                ('nif', models.CharField(blank=True, max_length=30, null=True, verbose_name="Numéro d'identification fiscale")),
                ('adresse', models.CharField(blank=True, max_length=30, null=True, verbose_name='Adresse')),
                ('tel', models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='Email')),
                ('form_ju', models.CharField(blank=True, choices=[('sarl', 'sarl'), ('eurl', 'eurl'), ('spa', 'spa')], max_length=30, null=True, verbose_name='Forme juridique')),
                ('nom_prop_ger', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nom du propriétaire ou du gérant')),
                ('reg_comm', models.CharField(blank=True, max_length=30, null=True, verbose_name='Registre de commerce')),
                ('deg_qual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Degré de la qualification professionnelle (pour les ETB-TCE)')),
                ('moy_chif', models.CharField(blank=True, max_length=30, null=True, verbose_name="Bilans des trois dernières années (moyenne du chiffre d'affaires) ")),
                ('note_eval', models.IntegerField(blank=True, null=True, verbose_name="Note d'évaluation")),
            ],
        ),
        migrations.CreateModel(
            name='Utils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name="L'année commerciale actuelle")),
                ('dm', models.IntegerField(verbose_name='Durée de traitement de Dossiers du service marché')),
                ('db', models.IntegerField(verbose_name='Durée de traitement de Dossiers du service budget')),
                ('dc', models.IntegerField(verbose_name='Durée de traitement de Dossiers du service comptable')),
                ('dco', models.IntegerField(verbose_name='Durée de traitement de Dossiers du service commande')),
            ],
        ),
        migrations.RenameField(
            model_name='dossier',
            old_name='engagement',
            new_name='date_eng_cf',
        ),
        migrations.RenameField(
            model_name='dossier',
            old_name='lancement',
            new_name='date_lanc',
        ),
        migrations.RenameField(
            model_name='dossier',
            old_name='mandatement',
            new_name='date_mandat',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='bonc',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='bonr',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='complement',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='convention',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='coulB',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='coulC',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='coulCo',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='coulM',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='dbonc',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='decisionC',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='decisionCo',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='decisionM',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='dproforma',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='duree',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='dureeB',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='dureeC',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='dureeCo',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='dureeM',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='définitive',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='motifClo',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='motifs',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='num',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='observationB',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='observationM',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='observationsC',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='pB',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='pC',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='pCo',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='pM',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='paiement',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='pieces',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='prestation',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='proformaCo',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='prolongation',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='recB',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='recC',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='recCo',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='respB',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='respC',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='respClo',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='respCo',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='respM',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='transmissionB',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='transmissionM',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='type_dossier',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='visa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='dossier',
            name='agent_fichtech',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Nom de l'agent ayant validé la fiche technique"),
        ),
        migrations.AddField(
            model_name='dossier',
            name='ancien_num',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ancien numéro du dossier'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='autre_docs',
            field=models.FileField(blank=True, max_length=10, null=True, upload_to='storage', verbose_name='Autres Documents'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='bon_comm',
            field=models.FileField(blank=True, null=True, upload_to='storage', verbose_name='Bon de commande signé'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='bord_dos_b',
            field=models.FileField(blank=True, null=True, upload_to='storage', verbose_name="Bordereau d'envoi"),
        ),
        migrations.AddField(
            model_name='dossier',
            name='bord_dos_c',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Borderau du dossier (commandes)'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='bord_dos_compt',
            field=models.FileField(blank=True, null=True, upload_to='storage', verbose_name='Bordereau du dossier au service comptable'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='bord_dos_m',
            field=models.FileField(blank=True, null=True, upload_to='storage', verbose_name='Bordereau dossier (marché)'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='bord_envoi',
            field=models.FileField(blank=True, null=True, upload_to='storage', verbose_name="Bordereau d'envoi"),
        ),
        migrations.AddField(
            model_name='dossier',
            name='contrat',
            field=models.FileField(blank=True, null=True, upload_to='storage', verbose_name='Contrat'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_bon_comm',
            field=models.DateField(blank=True, null=True, verbose_name='Date de signature du bon de commande'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_clot_init',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Date de clôture du contrôle initial'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_depo_offre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de déposition des offres'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_eval',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'évaluation"),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_fac_def',
            field=models.DateField(blank=True, null=True, verbose_name='Date Facture définitive'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_fac_prof',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la facture proforma'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_ouverture_plis',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date et heure de l'ouverture des plis"),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_paiement',
            field=models.DateField(blank=True, null=True, verbose_name='Date du paiement'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_rec_budg',
            field=models.DateField(blank=True, null=True, verbose_name='Date de réception du dossier au service budget'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_rec_comm',
            field=models.DateField(blank=True, null=True, verbose_name='Date de réception du dossier au service commandes'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_rec_compt',
            field=models.DateField(blank=True, null=True, verbose_name='Date de réception au service comptable'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_rec_prest',
            field=models.DateField(blank=True, null=True, verbose_name='Date de réception de prestation'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_retour_budg',
            field=models.DateField(blank=True, null=True, verbose_name='Date de retour au service budget'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_retour_comm',
            field=models.DateField(blank=True, null=True, verbose_name='Date de retour au service commandes'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_retour_marche',
            field=models.DateField(blank=True, null=True, verbose_name='Date de retour au service marché'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_sign_mand',
            field=models.DateField(blank=True, null=True, verbose_name='Date de signature du mandat'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_trans_budget',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'envoi au service Budget"),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_trans_budget2',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'envoi au service Budget"),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_trans_comm',
            field=models.DateField(blank=True, null=True, verbose_name='Date de transmission au service commande'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_trans_compt',
            field=models.DateField(blank=True, null=True, verbose_name="Date de transmission à l'agent comptable"),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_valid_fichtech',
            field=models.DateField(blank=True, null=True, verbose_name='Date de validation de la fiche technique'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_visa',
            field=models.DateField(blank=True, null=True, verbose_name='Date de visa'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='dec',
            field=models.CharField(blank=True, choices=[('', ''), ('Acceptation', 'Acceptation'), ('Infructuosité', 'Infructuosité'), ('Annulation/rejet', 'Annulation/rejet'), ('Autre', 'Autre')], max_length=20, null=True, verbose_name='Décision'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='dec_b',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Décision'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='dec_compt',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Décision (service comptable)'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='desist_soum',
            field=models.TextField(blank=True, null=True, verbose_name='En cas de désistement de soumissionnaire'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='doc_just_prest',
            field=models.FileField(blank=True, null=True, upload_to='storage', verbose_name='Document justifiant le déroulement de la prestation'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='dos_trans',
            field=models.FileField(blank=True, null=True, upload_to='storage', verbose_name='Dossier complet envoyé vers le service commande'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='fich_regul',
            field=models.FileField(blank=True, null=True, upload_to='storage', verbose_name='Fiche de régularisation signé'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='fich_tech',
            field=models.FileField(blank=True, null=True, upload_to='storage', verbose_name='Fiche technique validée'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='letr_desist',
            field=models.FileField(blank=True, null=True, upload_to='storage', verbose_name='Lettre de désistement'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='mandat',
            field=models.FileField(blank=True, null=True, upload_to='storage', verbose_name='Mandat de paiement signé'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='montant_c',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Montant'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='montant_fac_def',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Montant'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True, verbose_name='Motifs de rejet éventuel'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='motif_rejet_compt',
            field=models.TextField(blank=True, null=True, verbose_name='Motif du rejet éventuel'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='motif_retour_marche',
            field=models.TextField(blank=True, null=True, verbose_name='La raison de retour du dossier'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='note_rejet',
            field=models.FileField(blank=True, null=True, upload_to='storage', verbose_name='Note de rejet éventuel scannée'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='num_bon_comm',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='N° Bon de Commande'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='num_bon_rec',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='N° bon de réception'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='num_contrat',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='N° de Contrat'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='num_fac_def',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='N° de facture définitive'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='num_fac_prof',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='N° de facture proforma'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='obsM',
            field=models.TextField(blank=True, null=True, verbose_name='Observations'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='obs_annul',
            field=models.TextField(blank=True, null=True, verbose_name='Observations (Infructuosité/Annulation)'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='obs_b_rejet',
            field=models.TextField(blank=True, null=True, verbose_name='Observations sur la décision en cas de rejet'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='obs_c',
            field=models.TextField(blank=True, null=True, verbose_name='Observations'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='obs_eval',
            field=models.TextField(blank=True, null=True, verbose_name="Observation d'évaluation"),
        ),
        migrations.AddField(
            model_name='dossier',
            name='obs_ouver',
            field=models.TextField(blank=True, null=True, verbose_name="Observation d'ouverture"),
        ),
        migrations.AddField(
            model_name='dossier',
            name='obs_piec_complet',
            field=models.TextField(blank=True, null=True, verbose_name='Observations (Pièces à compléter)'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='obs_prest',
            field=models.TextField(blank=True, null=True, verbose_name='Observations sur la prestation'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='obs_rejet_budg',
            field=models.TextField(blank=True, null=True, verbose_name='Observations sur la décision en cas de rejet'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='obs_suivi_comm',
            field=models.TextField(blank=True, null=True, verbose_name='Observations sur le suivi des commandes'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='pv_annul',
            field=models.FileField(blank=True, null=True, upload_to='storage', verbose_name="PV d'annulation"),
        ),
        migrations.AddField(
            model_name='dossier',
            name='pv_eval',
            field=models.FileField(blank=True, null=True, upload_to='storage', verbose_name='PV Evaluation'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='pv_infruc',
            field=models.FileField(blank=True, null=True, upload_to='storage', verbose_name="PV d'infructuosité"),
        ),
        migrations.AddField(
            model_name='dossier',
            name='rapp_present',
            field=models.FileField(blank=True, null=True, upload_to='storage', verbose_name='Rapport de présentation'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='resp_compt',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Responsable du suivi du dossier au service comptable'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='resp_qual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Responsable de qualité'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='resp_qual_C',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Responsable de qualité au service commandes'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='resp_qual_b',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Responsable qualité dans le service budget'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='resp_qual_compt',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Responsable Qualité au service comptable'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='resp_suivi_C',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Responsable du suivi au service commandes'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='resp_suivi_b',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Responsable du suivi du dossier dans le service budget'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='resp_suivi_m',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Responsable du suivi du dossier'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='sys_eval',
            field=models.CharField(blank=True, choices=[('', ''), ('Système de notation', 'Système de notation'), ('Le moins Disant', 'Le moins Disant')], max_length=30, null=True, verbose_name="Système d'évaluation"),
        ),
        migrations.AddField(
            model_name='dossier',
            name='typ_comm',
            field=models.CharField(blank=True, choices=[('Commande consultation', 'Commande consultation'), ('Commande directe', 'Commande directe'), ('', '')], max_length=30, null=True, verbose_name='Types de commande'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='type_paiement',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Type de paiement'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='valid_c',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=30, null=True, verbose_name='Dossier valide pour l’envoi au service budget ?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profil',
            field=models.CharField(blank=True, choices=[('Administrateur', 'Administrateur'), ('Consultation', 'Consultation'), ('Consultation/Modification', 'Consultation/Modification'), ('Ordonnateur', 'Ordonnateur')], max_length=30, null=True, verbose_name='Type du Profile'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='num_dossier',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numéro du dossier'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='objet',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Objet'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='adresse',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='num',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numéro de Téléphone'),
        ),
        migrations.CreateModel(
            name='Depositaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(blank=True, max_length=30, null=True, verbose_name='Opérateur')),
                ('lot', models.ManyToManyField(to='suivi.Lot', verbose_name="Lot dont lequel l'opérateur dépose une offre")),
            ],
        ),
        migrations.AddField(
            model_name='dossier',
            name='depositaires',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='suivi.depositaire', verbose_name='Liste des soumissionaires ayant déposé leur offre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dossier',
            name='lots',
            field=models.ManyToManyField(blank=True, to='suivi.Lot', verbose_name='Lots'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='operateurs',
            field=models.ManyToManyField(blank=True, to='suivi.Operateur', verbose_name='Liste des soumissionaires ayant retiré la fiche technique'),
        ),
    ]
