# Generated by Django 3.2.9 on 2022-10-02 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0002_auto_20221002_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='depositaires',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.depositaire', verbose_name='Liste des soumissionaires ayant déposé leur offre'),
        ),
    ]
