# Generated by Django 3.2.9 on 2022-10-03 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0003_alter_dossier_depositaires'),
    ]

    operations = [
        migrations.CreateModel(
            name='Op_Dos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(blank=True, choices=[('Retirant', 'Retirant'), ('Dépositaire', 'Dépositaire'), ('Fournisseur', 'Fournisseur')], max_length=30, null=True, verbose_name="Statut de l'opérateur au niveau du dossier")),
            ],
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='depositaires',
        ),
        migrations.DeleteModel(
            name='Depositaire',
        ),
        migrations.AddField(
            model_name='op_dos',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.dossier', verbose_name='Dossier'),
        ),
        migrations.AddField(
            model_name='op_dos',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.lot', verbose_name='Lot choisi par le dépositaire'),
        ),
        migrations.AddField(
            model_name='op_dos',
            name='op',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.operateur', verbose_name='Opérateur'),
        ),
    ]
