# Generated by Django 3.2.9 on 2022-10-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0005_op_dos_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='op_dos',
            name='ordre',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ordre du soumissionaire'),
        ),
    ]
